language: ruby
cache: bundler
script: bundle exec rake release_checks
before_install:
- gem update system
matrix:
  fast_finish: true
  include:
  - rvm: 2.3.4
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent PUPPET_GEM_VERSION="5.3.2" BEAKER_debug=true BEAKER_set=docker/ubuntu-14.04
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.3.4
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent PUPPET_GEM_VERSION="5.3.2" BEAKER_debug=true BEAKER_set=docker/ubuntu-16.04
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.3.4
    bundler_args: "--without system_tests"
    env: PUPPET_GEM_VERSION="5.3.2"
  - rvm: 2.3.4
    bundler_args: "--without system_tests"
    env: PUPPET_GEM_VERSION="~> 5.0"
  - rvm: 2.3.4
    bundler_args: "--without system_tests"
    env: PUPPET_GEM_VERSION="~> 6.0"
notifications:
  email: false
