language: ruby
cache: bundler
before_install:
- gem update system
- gem update bundler
- bundle --version
- rm -f Gemfile.lock
script:
  - cat Gemfile.lock
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
  - rvm: 2.3.4
    env: CHECK=beaker PUPPET_INSTALL_TYPE=agent PUPPET_GEM_VERSION="~> 5.0" BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=ubuntu1604-64 BEAKER_HYPERVISOR=docker BEAKER_debug=true
    services: docker
    sudo: required
  - rvm: 2.3.4
    env: CHECK=beaker PUPPET_INSTALL_TYPE=agent PUPPET_GEM_VERSION="~> 5.0" BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=centos7-64 BEAKER_HYPERVISOR=docker BEAKER_debug=true
    services: docker
    sudo: required
  - rvm: 2.3.4
    env: CHECK=beaker PUPPET_INSTALL_TYPE=agent PUPPET_GEM_VERSION="~> 6.0" BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=ubuntu1604-64 BEAKER_HYPERVISOR=docker BEAKER_debug=true
    services: docker
    sudo: required
  - rvm: 2.3.4
    env: CHECK=beaker PUPPET_INSTALL_TYPE=agent PUPPET_GEM_VERSION="~> 6.0" BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=centos7-64 BEAKER_HYPERVISOR=docker BEAKER_debug=true
    services: docker
    sudo: required
  - rvm: 2.3.4
    bundler_args: --without system_tests
    env: CHECK=release_checks PUPPET_GEM_VERSION="5.3.2"
  - rvm: 2.3.4
    bundler_args: --without system_tests
    env: CHECK=release_checks PUPPET_GEM_VERSION="~> 5.0"
  - rvm: 2.3.4
    bundler_args: --without system_tests
    env: CHECK=release_checks PUPPET_GEM_VERSION="~> 6.0"
notifications:
  email: false
